name: Demo Workflow
on: [push,workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the TechTuesday repository
        run: |
          ls ${{ github.workspace }}
